apiVersion: v1
kind: Service
metadata:
  name: rickandmorty-service
  namespace: develop
spec:
  selector:
    app: rickandmorty
  ports:
    - protocol: TCP
      port: 3000        # Puerto expuesto dentro del cluster
      targetPort: 3000  # Puerto del contenedor
  type: ClusterIP       # Opciones: ClusterIP (default), NodePort, LoadBalancer